spring.application.name=API-GETWAY
server.port=8081

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Fix shutdown error
eureka.client.should-unregister-on-shutdown=false

spring.cloud.compatibility-verifier.enabled=false
